FROM acrelle/rpi-mqtt

LABEL maintainer="anthony@relle.co.uk"

RUN [ "cross-build-start" ]

RUN mkdir -p /app/mqtt-launcher/ && \
 git clone https://github.com/jpmens/mqtt-launcher /app/mqtt-launcher/

RUN [ "cross-build-end" ]

ENV MQTTLAUNCHERCONFIG=/config/mqtt-launcher.conf

COPY start.sh /app

CMD [ "/app/mqtt-launcher/mqtt-launcher.py" ]
