version: '2'
services:
  mqtt:
    build: .
    image: acrelle/mqtt:rpi
    container_name: mqtt
    privileged: true
    volumes:
     - ~/appdata/mqtt/config:/config
    environment:
     - PUID=1001
     - PGID=100
    restart: always
    tty: true
    command: watch -n 60 /config/get_climate.sh
    working_dir: /config
