version: '2'
services:
  mqtt-lirc:
    build: .
    image: acrelle/mqtt-lirc:rpi
    container_name: mqtt-lirc
    privileged: true    
    devices:
      - /dev/lirc0:/dev/lirc0"
    volumes:
     - ~/appdata/mqtt-lirc/config:/config
    environment:
     - PUID=1001
     - PGID=100
     - MQTTLAUNCHERCONFIG=/config/mqtt-launcher.conf
    restart: always
